---

all:
  children:
    controllers:
      hosts:
        controller:
          ansible_host: 192.168.56.10
    servers:
      hosts:
        server1:
          ansible_host: 192.168.56.11
        server2:
          ansible_host: 192.168.56.12

