---
- name: Provision Controller
  hosts: controller
  become: true
  tasks:
    - name: Generate ssh key for `student'
      become: yes
      ansible.builtin.user:
        name: student
        generate_ssh_key: yes
        key_type: rsa
        ssh_key_bits: 2048
        ssh_key_file: /home/student/.ssh/id_rsa
        ssh_key_passphrase: ""
        state: present
    - name: Ensure the private key has correct permission
      ansible.builtin.file:
        path: /home/student/.ssh/id_rsa
        mode: '0600'
        owner: student
        group: student
    - name: Read student's public key
      ansible.builtin.slurp:
        src: /home/student/.ssh/id_rsa.pub
      register: student_pubkey
    - name: Install Controller Packages
      dnf:
        name:
          - lsb_release
        state: present
        update_cache: yes
        
- name: Provision All Hosts
  hosts: all
  become: true
  tasks:
    - name: Validate student ssh directory
      file: /home/student/.ssh state=directory owner=student group=student mode=0700
    - name: Provision 'ansible' identity on all hosts
      user:
        name: ansible
        state: present
        shell: /bin/bash
        groups: wheel
        append: yes
        create_home: yes
    - name: Provision 'student' identity on all hosts
      user:
        name: student
        state: present
        shell: /bin/bash
        groups: wheel
        append: yes
        create_home: yes
    - name: Distribute the public key to all hosts
      ansible.builtin.authorized_key:
        user: student
        state: present
        key: "{{ hostvars['controller']['student_pubkey']['content'] | b64decode }}"
    - name: Ensure the private key has correct permission
      file:
        path: /home/student/.ssh/id_rsa
        mode: '0600'
        owner: student
        group: student
    - name: Install packages
      dnf:
        name:
          - ansible
          - python3-pip
        state: present
        update_cache: yes
