# -*- mode: ruby -*-
# vi: set ft=ruby :

#############
# VARIABLES #
#############

ISO_PATH="./automation/iso/Rocky-9.7-x86_64-minimal.iso"
BOX_IMAGE="generic/rocky9"
HOSTONLY_IP="192.168.56.1"
CONTROLLER_NAME="controller"
CONTROLLER_IP="192.168.56.10"
SERVER1_NAME="server1"
SERVER1_IP="192.168.56.11"
SERVER2_NAME="server2"
SERVER2_IP="192.168.56.12"
BRIDGE_INTERFACE="MediaTek MT7921 Wi-Fi 6 802.11ax PCIe Adapter"
CONTROLLER_RAM=4096
SERVER_RAM=3072
CPU_COUNT=2
CONTROLLER_DISK_MB=40960
SERVER_DISK_MB=30720
SYNCED_FOLDER_HOST="./"
SYNCED_FOLDER_GUEST="/vagrant"

Vagrant.configure("2") do |config|

  config.vm.box = BOX_IMAGE
  config.vm.synced_folder ".", "/vagrant", disabled: false
  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
     vb.gui = false
     vb.cpus = CPU_COUNT
   end

    config.vm.define "server1" do |server1|
      server1.vm.hostname = SERVER1_NAME
      server1.vm.network "private_network", ip: SERVER1_IP
      server1.vm.network "public_network", bridge: BRIDGE_INTERFACE
      server1.vm.provider "virtualbox" do |vb|
                vb.name=SERVER1_NAME
                vb.memory = SERVER_RAM
      end
      server1.vm.provision "shell", inline: <<-SHELL
              echo "Server1 shell provisioning hook executed"
      SHELL
    end

    config.vm.define "server2" do |server2|
      server2.vm.hostname = SERVER2_NAME
      server2.vm.network "private_network", ip: SERVER2_IP
      server2.vm.network "public_network", bridge: BRIDGE_INTERFACE
      server2.vm.provider "virtualbox" do |vb|
                vb.name=SERVER2_NAME
                vb.memory = SERVER_RAM
      end
      server2.vm.provision "shell", inline: <<-SHELL
              echo "Server2 shell provisioning hook executed"
      SHELL
    end

   config.vm.define "controller" do |controller|
      controller.vm.hostname = CONTROLLER_NAME
      controller.vm.network "private_network", ip: CONTROLLER_IP
      controller.vm.network "public_network", bridge: BRIDGE_INTERFACE
      controller.vm.provider "virtualbox" do |vb|
                vb.name=CONTROLLER_NAME
                vb.memory = CONTROLLER_RAM
      end
      controller.vm.provision "shell", inline: <<-SHELL
              echo "Controller shell provisioning hook executed"
              sudo dnf install -y ansible
              git clone https://github.com/TheSubtleArtist/myLinuxTraining.git
              cd /myLinuxTraining/automation/ansible
              ansible-playbook -i inventory provision.yml
      SHELL
    end


  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
