# -*- mode: ruby -*-
# vi: set ft=ruby :

#############
# VARIABLES #
#############

LAB_NAME_PREFIX=linuxplus
ISO_PATH="./automation/iso/Rocky-9.7-x86_64-minimal.iso"
BOX_IMAGE="rockylinux/9"
HOSTONLY_IP="192.168.56.1"
CONTROLLER_NAME="controller"
CONTROLLER_IP="192.168.56.10"
SERVER1_NAME="server1"
SERVER1_IP="192.168.56.11"
SERVER2_NAME="server2"
SERVER2_IP="192.168.56.12"
CONTROLLER_RAM=4096
SERVER_RAM=3072
CPU_COUNT=2
CONTROLLER_DISK_MB=40960
SERVER_DISK_MB=30720
SYNCED_FOLDER_HOST="./"
SYNCED_FOLDER_GUEST="/vagrant"

Vagrant.configure("2") do |config|

  config.vm.box = "base"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Disable the default share of the current code directory. Doing this
  # provides improved isolation between the vagrant box and your host
  # by making sure your Vagrantfile isn't accessible to the vagrant box.
  # If you use this you may want to enable additional shared subfolders as
  # shown above.
  config.vm.synced_folder ".", "/vagrant", disabled: false

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
     vb.gui = false
     vb.cpus = CPU_COUNT
   end

   config.vm.define "controller" do |controller|
      controller.vm.hostname = CONTROLLER_NAME
      controller.vm.network "private_network", ip: CONTROLLER_IP
      controller.vm.network "public_Network", bridge: nil
      controller.vm.provider "virtualbox" do |vb|
                vb.name=CONTROLLER_NAME
                vb.memory = CONTROLLER_RAM
      end
      controller.vm.provisioin "shel", inline: <<-SHELL
              echo "Controller shell provisioning hook executed"
      SHELL
    end

    config.vm.define "server1" do |server1|
      server1.vm.hostname = SERVER1_NAME
      server1.vm.network "private_network", ip: SERVER1_IP
      server1.vm.network "public_Network", bridge: nil
      server1.vm.provider "virtualbox" do |vb|
                vb.name=SERVER1_NAME
                vb.memory = SERVER_RAM
      end
      server1.vm.provision "shell", inline: <<-SHELL
              echo "Server1 shell provisioning hook executed"
      SHELL
    end

    config.vm.define "server2" do |server2|
      server2.vm.hostname = SERVER2_NAME
      server2.vm.network "private_network", ip: SERVER2_IP
      server2.vm.network "public_Network", bridge: nil
      server2.vm.provider "virtualbox" do |vb|
                vb.name=SERVER2_NAME
                vb.memory = SERVER_RAM
      end
      server2.vm.provision "shell", inline: <<-SHELL
              echo "Server2 shell provisioning hook executed"
      SHELL
    end

  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
