# -*- mode: ruby -*-
# vi: set ft=ruby :

#############
# VARIABLES #
#############

BOX_IMAGE="generic/rocky9"
HOSTONLY_NAME="VirtualBox Host-Only Ethernet Adapter"

Vagrant.configure("2") do |config|

  config.vm.box = BOX_IMAGE
  config.vm.synced_folder ".", "/vagrant", disabled: false
  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
     vb.gui = false
     vb.cpus = 2
   end
   config.vm.provision "shell", inline: <<-SHELL
      echo "Global shell provisioning hook executing"
   SHELL

    servers = [
    { name: "server1", ip: "192.168.56.11", memory: 3072, disk_gb: 30 },
    { name: "server2", ip: "192.168.56.12", memory: 3072, disk_gb: 30 }
    ]
  servers.each do |srv|
    config.vm.define srv[:name] do |node|
      node.vm.hostname = srv[:name]
      node.vm.network "private_network", ip: srv[:ip], name: HOSTONLY_NAME
      node.vm.provider "virtualbox" do |vb|
                vb.name=srv[:name]
                vb.memory = srv[:memory]
      end
      node.vm.provision "shell", inline: <<-SHELL
              echo "Server shell provisioning hook executed"
              install -d -m 700 -o vagrant -g vagrant /home/vagrant/.ssh
              PUBKEY="/vagrant/bootstrap-keys/bootstrap_id_rsa.pub"
              grep -qxF "$(cat ${PUBKEY})" /home/vagrant/.ssh/authorized_keys || cat ${PUBKEY} >> /home/vagrant/.ssh/authorized_keys
              chown vagrant:vagrant /home/vagrant/.ssh/authorized_keys
              chmod 600 /home/vagrant/.ssh/authorized_keys
              echo "#{srv[:name]} shell provisioning hook executed"
      SHELL
    end
  end

   config.vm.define "controller" do |controller|
      controller.vm.hostname = "controller"
      controller.vm.network "private_network", ip: "192.168.56.10", name: HOSTONLY_NAME
      controller.vm.provider "virtualbox" do |vb|
                vb.name="controller"
                vb.memory = 4096
      end
      controller.vm.provision "shell", inline: <<-SHELL
              echo "Controller shell provisioning hook executed"
              install -d -m 700 -o vagrant -g vagrant /home/vagrant/.ssh
              cat /vagrant/bootstrap-keys/bootstrap_id_rsa >> /home/vagrant/.ssh/bootstrap_id_rsa
              chown vagrant:vagrant /home/vagrant/.ssh/bootstrap_id_rsa
              chmod 600 /home/vagrant/.ssh/bootstrap_id_rsa
              echo "SSH key setup completed on controller"
              git clone https://github.com/TheSubtleArtist/myLinuxTraining.git

      SHELL
    end


  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
